// NAO E A MELHOR PRATICA PARA ACESSAR, ESTA PUBLICO (FORMA CORRETA, VARIVEL DE AMBIENTE OU SERVICO DE CONFIGURACAO)
//https://docs.nestjs.com/security/authentication
export const jwtConstants = {
    secret: 'DO NOT USE THIS VALUE. INSTEAD, CREATE A COMPLEX SECRET AND KEEP IT SAFE OUTSIDE OF THE SOURCE CODE.',
};